### ISSUE TITLE
Данные рекламации

### ISSUE THREAD

**Issue by igorgo** [igorgo/web-udp-interface#1]
- [x] Получение данных
- [ ]  Дизайн

**Comment by igorgo** [comment]
Получение данных сделано.

**Comment by igorgo** [comment]
Необходимо красиво отобразить событие в компоненте `src/components/claims/claim/ClaimCard.vue`

**Comment by Lucky0ne** [comment]
В процессе

**Comment by igorgo** [comment]
Пока хватит )))
